quidditch/config/routes.rb
Rails.application.routes.draw do
  get 'games/home' => 'games#home'

  get 'games/start' => 'games#start'

  get 'games/show_statistics' => 'games#show_statistics', as: 'show_statistics'

  patch 'games/update_statistics' => 'games#update_statistics', as: 'update_statistics'

  root 'games#home'

end

quidditch/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

quidditch/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
end

quidditch/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

quidditch/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def home
  end

  def start
    @gryffindor_players = Team.find_by_name("Gryffindor").players
    @hufflepuff_players = Team.find_by_name("Hufflepuff").players
  end

  def update_statistics
    params.each do |key, value|
      if key.include? "winner"
        if value != "nil"
          team_id = value.to_i + 1
          @team = Team.find(team_id)
          total_wins = @team.total_wins + 1
          @team.update_column(:total_wins, total_wins)
        end
      elsif key.include? "player"
        @player = Player.find_by_name(key.split("_")[1])
        total_score = @player.total_lifetime_score + value.to_i
        @player.update_column(:total_lifetime_score, total_score)
      end  #end of if key.include? "winner"
    end  #end of params.each do |key, value|
  end  # end of def
  
  def show_statistics
    @teams = Team.all
    @players = Player.all
  end
  
end

quidditch/app/helpers/application_helper.rb
module ApplicationHelper
end

quidditch/app/helpers/games_helper.rb
module GamesHelper
end

quidditch/app/views/games/home.html.erb
<body class="home_background" background="/assets/home_background.jpg">
	<a href="/games/start" title="Start the Game"><img class="start_button" src="/assets/start.png"></a>
	<a href="/games/show_statistics" title="Show Stats"><img class="show_stats" src="/assets/stats.png"></a>
</body>

quidditch/app/views/games/show_statistics.html.erb
<body class="stats_background" background="/assets/stats_background.jpg">
	<a href="/games/home" title="Back to Home"><img class="back_to_home" src="/assets/back_button.png"></a>
	<h1>Matches Won</h1>
	<% @teams.each do |team| %>
		<h2><%= team.name %>: &nbsp;<%= team.total_wins %></h2>
	<% end %>
	<br/>
	<h1>Players and their Lifetime Scores</h1>
	<% @players.each do |player| %>
		<h3><%= player.name %>: &nbsp;<%= player.total_lifetime_score %></h3>
	<% end %>
</body>

quidditch/app/views/games/start.html.erb
<body class="match_background" background="/assets/match_background.jpeg">
	<a href="/games/home" title="Back to Home"><img class="back_to_home" src="/assets/back.png"></a>
	<div id="match_result">
	</div>	
	<%= form_tag update_statistics_path , :id => "update_stats_form", :method => :patch, :remote => true  do %>
		<div>
			<h1>Team Gryffindor</h1>
			<% @gryffindor_players.each do |player| %>
				<p><%= player.name %></p>
				<%= hidden_field_tag("player_" + player.name, 0) %> 
			<% end %>
			<p id="team_0_score"><b>Score: 0</b></p>
			<h1>Team Hufflepuff</h1>
			<% @hufflepuff_players.each do |player| %>
				<p><%= player.name %></p>
				<%= hidden_field_tag("player_" + player.name, 0) %>
			<% end %>
			<p id="team_1_score"><b>Score: 0</b></p>
		</div>
		<div id="match_stats">
			<h1>Match Stats</h1>
		</div>
		<%= hidden_field_tag("winner", "nil") %>
	<% end %>
</body>
<script>
    var count = 0; // will store the time elapsed in seconds
    score_array = [0,0]; // will contain gryffindor's score at 0th index and hufflepuff's score at 1st index
    players_name_array = [];  // will contain names of all the gryffindor's players from 0th to 3rd position and all hufflepuff's players from 4th to 7th position
	team_name_array = ["gryffindor","hufflepuff"];
	<% @gryffindor_players.each do |player| %>
		players_name_array.push("<%= player.name %>")
	<% end %>
	<% @hufflepuff_players.each do |player| %>
		players_name_array.push("<%= player.name %>")
	<% end %>
	$(document).ready(function(){
		chance_to_score_var = setInterval(function(){
				chance_to_score(); // there is a chance to score for one team after every 5 seconds
			},5000);
	});
	function chance_to_score(){  // this function decides which team has a chance to score and if it scored
		count = count + 5;  // updating the elapsed time value
		which_team = Math.floor(Math.random()*2); //will decide which team has a chance to score
		which_player = Math.floor(Math.random()*4); //will decide which player has a chance for goal or if it's a fetching golden ball chance
		if (which_player == 0) //chance for the golden ball (the first player from both the teams are for fetching the golden ball only and they aren't allowed to score a goal)
		{
			if (count > 120 && score_array[which_team] > 80)  //only team with score more than 80 can fetch a golden ball and not before two minutes
			{
				if ( (score_array[which_team] >= 120 && Math.random() < 0.5) || (score_array[which_team] < 120 && Math.random() < 0.005) )  //golden ball fetched. If the first condition (before ||) is true, the team wins, but if the second condition is true i.e. the team couldn't reach a score of 200 and it fetched the golden ball, it loses
				{
					window.clearInterval(chance_to_score_var); // the match always ends with fetching of the golden ball
					score_array[which_team] = score_array[which_team] + 80;  // updating the team's score
					$("#team_" + which_team + "_score").html("<b>Score: " + score_array[which_team] + "</b>"); //updating the team's score display
					team_which_scored = team_name_array[which_team]; //name of the team which scored
					player_which_scored = players_name_array[which_player + (which_team * 4)];	//name of the player who scored
					score = parseInt($("#player_" + player_which_scored).attr("value")) + 80;  //scoring player's total match score
					$("#player_" + player_which_scored).attr("value", score);	//updating the scoring player's total match score
					$("#match_stats").append("<p>Team " + team_which_scored + ", player " + player_which_scored + " fetched the golden ball at " + count + " seconds.</p>");  // adding to the match's stats.
					if (score_array[which_team] >= 200)  //checking whether the team reached the score of 200 after fetching the golden ball, if not, it loses
					{
						$("#match_result").html("<b> Match Result </b> <p> Team " + team_name_array[which_team] + " wins the match! </p>"); // showing the final match result
						$("#winner").attr("value",which_team);  // setting the winner team value
					}
					else
					{
						$("#match_result").html("<b> Match Result </b> <p> Team " + team_name_array[Math.abs(which_team - 1)] + " wins since the other team fetched the golden ball and their score didn't reach 200. </p>"); //showing the final match result
						$("#winner").attr("value",Math.abs(which_team - 1));  // setting the winner team value
					}
					$("#update_stats_form").submit(); // sending request to server side to update the stats
				}
			}
		}
		else
		{	
			if (score_array[which_team] < 190)  // a team can't score a goal if it has reached a score of 190, it can end the game now only by fetching the golden ball
			{
				team_which_scored = team_name_array[which_team]; //name of the team which scored
				player_which_scored = players_name_array[which_player + (which_team * 4)]; // name of the player which scored
				score = parseInt($("#player_" + player_which_scored).attr("value")) + 10;
				$("#player_" + player_which_scored).attr("value", score);	//updating total match score of the scoring player
				$("#match_stats").append("<p>Team " + team_which_scored + ", player " + player_which_scored + " scored at " + count + " seconds.</p>");  //adding to the match stats
				score_array[which_team] = score_array[which_team] + 10;  // updating the team's score
			}
		}
		$("#team_" + which_team + "_score").html("<b>Score: " + score_array[which_team] + "</b>");  // updating the team's score display
		if (count == 300 && $("#winner").attr("value") == "nil")  // the time is already 5 minutes and so the game should end.
		{
			window.clearInterval(chance_to_score_var); // since the game ends at 5 minutes, no matter what, so clearing the call to chance_to_score function
			$("#update_stats_form").submit(); // sending request to server side to update the stats
			$("#match_result").html("<b> Match Result </b> <p> Match is a draw since it's already 5 minutes and no team can reach a score of 200. </p>"); //showing the final match result
		}
	}
</script>

quidditch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quidditch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>